name: Example

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actionhippie/gpgsign@v1
        with:
          private_key: ${{ secrets.GNUPG_KEY }}
          passphrase: ${{ secrets.GNUPG_PASSPHRASE }}
          detach_sign: false
          files: |
            ./*
                
      - run: |
          dir
